gollum/gollum

lib/gollum/app.rb
This fixes URI::InvalidURIError when browsing the history of a page with unicode characters in its title (possible with the rugged adapter).
=> Encode the page title in the URL of a diff page

lib/gollum/app.rb, lib/gollum/helpers.rb
There was a bug when mounting gollum as rack app: the new `:allow_editing` option in the wiki's option hash would default to false. See https://github.com/gollum/gollum/issues/911. However, https://github.com/gollum/gollum/commit/09149592b55d4a0e87296bb8a3acc3f9015a6c79 did not fix the issue completely. More specifically, it fixed it for GET requests, but not for POST requests.
This is because my previous fix only made the `@allow_editing` instance variable, and not the corresponding key in the options hash, default to true. So [this line](https://github.com/gollum/gollum/blob/master/lib/gollum/editing_auth.rb#L10) would stop any POST request.
My apologies. ;)
=> Set the allow_editing wiki option to true by default.

lib/gollum/public/gollum/livepreview/js/livepreview.js
Happens on firefox for both windows & linux. See #952.
Before
After
=> pixel tweaks so the left scrollbar is selectable and the viewport takes the whole page

lib/gollum/app.rb
I'm running gollum from a `config.ru` file:
Precious::App.set(:wiki_options, {:universal_toc => false, :template_dir => 'templates'})
run Precious::App
and without this fix, it never reads my custom templates directory.
=> adding template dir logic to app.rb vs. just the bin

lib/gollum/app.rb, lib/gollum/public/gollum/livepreview/js/livepreview.js, lib/gollum/templates/layout.mustache, lib/gollum/templates/livepreview.mustache, lib/gollum/views/livepreview.rb
I moved live preview to the templates directory so the mathjax script is only included when mathjax is enabled.
=> enable mathjax in live preview

lib/gollum/public/gollum/javascript/editor/gollum.editor.js
Hi folks,
Uploading a file into the editor fails when the gollum wiki is running with base_path != '/'.   The fix is pretty simple.  By the way, I noticed that there is a post to /wiki/help in this same js file.  I'm not sure what that's for, but I imagine it needs a similar treatment.
best,
-Kirat
=> prepend baseUrl to /uploadFile

lib/gollum/templates/page.mustache
I found a couple of unclosed `li` tags that appear to do nothing (correct me if I'm wrong).
=> Remove extraneous li tags

lib/gollum/views/pages.rb, test/test_pages_view.rb
This pull request fixes #1012 that I opened earlier this week. The `/pages` view will now list all folders in the given base path alphabetically first, and then pages. I have also updated the tests for `/pages` to account for the changes.
While this should technically cover the changes in 1200afe, I think we may want to consider re-writing these tests or re-naming them, as they seem to only provide coverage for the `/Mordor` sub-folder. A better test would cover the root of the test repository because it contains more folders and a mix of upper- and lower-case pages.
I can write up a separate test for that situation if requested.
Sorry for the delay, Sinatra has been behaving funny on my arch install.
=> Fix #1012: /Pages View should list folders first, then files, all alphabetically

lib/gollum/public/gollum/livepreview/js/livepreview.js
Internet Explorer caches all AJAX get requests and decides when to expire
them in the cache. This commit disables caching on the GET request to
/data/<PAGE NAME>, which fixes IE displaying old page data when using the
live editor.
See http://www.dashbay.com/2011/05/internet-explorer-caches-ajax/ and
https://stackoverflow.com/questions/4303829/how-to-prevent-a-jquery-ajax-request-from-caching-in-internet-explorer
=> Fix #1030: Disable AJAX Cach in Live Editor

lib/gollum/app.rb, lib/gollum/templates/layout.mustache, lib/gollum/views/layout.rb
Because currently, gollum is only able to read custom files from the root directory - but when page-file-dir is set, the root directory is not accessible, making it impossible to load a custom.js or custom.css file.
=> Changed layout template, to handle custom.x with page-file-dir

bin/gollum
Allow users to change the PlantUML server endpoint when running gollum via a new --plantuml-url option. This requires gollum-lib rc version to work.
I guess is better to wait the next release of gollum-lib with PlantUML support and modify the Gemfile in gollum to use that version before this gets merged.
Is there a roadmap or an estimate on when the next gollum-lib version with PlantUML support is to be released?
=> Add option to configure PlantUML endpoint

lib/gollum/views/layout.rb, test/test_app.rb
Addresses problem introduced by https://github.com/gollum/gollum/pull/1047. Edit an existing test and add a new test to ensure that the path to custom.css/custom.js correctly reflects page-file-dir.
=> Fix custom.x path when page-file-dir is not set

README.md
Hi,
like i wrote in the Issue #1049, i use gollum with a CAS SSO server, so I made a wiki entry about this.
With this you can have RW access for some user specified in a config file, and everybody else have only RO access to the wiki.
Hope it my help someone.
=> README add link to wiki about CAS SSO

README.md, bin/gollum, config.rb, config.ru, gollum.gemspec
**EDIT:**
What I've changed:
These were added, with pointers to the wiki.
1. Added `opts.program_name = "gollum"`, just in case.
2. Options were divided into "categories", according to significance/purpose.
3. Deleted the `--gollum-path` option since it was completely redundant (in favour of ARGV).
4. Added short style options to several most important/used options.
4. Fixed several potential bugs and confusions:
* `--port` now raises an error if the arg is not an integer number.
* `--base-path` is now escaped before being used. While setting base path to a URL that needs not escaping STILL WORKS, the contrary DOESN'T WORK because there is an infinite redirect (**very probably another bug somewhere down the road**). To reproduce:
* `gollum -b "//wiki"`
* `http://localhost:4567`
* …
=> Config files restored + BIN enhancements + BIN/README sync

README.md
For some reason, numeric references to issues don't seem to work in README so I replaced the one used in Gollum to a manual link :).
=> Fixing the link to Windows support meta issue

bin/gollum
Just takes away all slashes at the start of a basepath instead of just removing the 'first' one.
Not sure how to add a proper spec for this, as the change was made directly at the cli.
=> Sanitize basepath options when adding with more than one / at the start Fixes #1066.

lib/gollum/app.rb, lib/gollum/views/page.rb
Use Gollum::Page#last_version instead of Gollum::Page#versions in the
cases identified in #1087:
* In Precious::App#show_page_or_file
* In Precious::Views::Page#author
* In Precious::Views::Page#date
=> Use `last_version` instead of `versions` when possible. Fixes #1087.

README.md
From [RubyGems](https://rubygems.org/gems/github-markdown/versions/0.6.9):
> THIS GEM IS NOT MAINTAINED AND NOT SUPPORTED.
Also, the GitHub repository, maintained by GitHub, was removed.
The link is now a redirect, it doesn't point to the GFM page anymore.
Do you want this replaced with something else? My understanding is that kramdown comes with everything needed, not entirely sure if something needs to be done to enable GFM support there.
=> Remove deprecated github-markdown markup

lib/gollum/app.rb
Permission checking was spread across `post` action handlers instead of inside the `before` to normalize between `get` and `post` action handlers and be more explicit.
This resolves #1140.
=> Fix compare page not accessible in no-edit mode. Resolves #1140.

lib/gollum/app.rb, lib/gollum/public/gollum/javascript/gollum.js, lib/gollum/templates/page.mustache, lib/gollum/views/page.rb, test/test_app.rb
As described in #1078:
Page loads in large repos (4000 files, 4000 commits) are slow (7 seconds and more)
* Almost all of this time is spent in `page.last_version`.
* This is  extra slow when using the `rugged_adapter`, as I think @joaquinvanschoren reported. That is because the `rugged_adapter` implements the relevant logic (in `Gollum::Git#versions_for_path`) in ruby, whereas `grit` ends up calling C-git, which is significantly faster.
Therefore:
* We've decided to eliminate the calls to `last_version` by default.
Impact:
* A call to `last_version` was used to determine whether the page had a history, so that in new pages, the 'History' minibutton would not be displayed. This check has been removed, so new pages will show the 'History' button (which will just come up empty).
* In the …
=> Remove calls to Page#last_version. Closes #1078.

lib/gollum/views/pages.rb
The page list collection logic was using the filename without any
scaping to create a regexp. This not only breaks for some names it might
even be a security problem by introducing bad regular expression as
filenames.
=> Fix page list for files that have regexp special chars.

test/test_unicode.rb
Empty name or email are not allowed by libgit2 and cause a test failure when the test suite is run against rugged_adapter.
Please refer to https://github.com/gollum/gollum/issues/1187#issuecomment-275672962 for a more detailed explanation.
=> Pass non-empty commit author details in transliteration test

lib/gollum/app.rb
When you create a file in a folder with non-ascii character, for exemple "Réseau", after creating the page, it throwed an "URI::InvalidURIError", given the fact that the url returned was "/Réseau/H%C3%A9y", only the part with the name of the file was correctly encoded.
So I propose to encode every part of the url to solve this issue.
=> Solve bug when folder contains non-ascii character

.travis.yml, README.md, bin/gollum, gollum.gemspec, lib/gollum/public/gollum/css/template.css, lib/gollum/templates/page.mustache, lib/gollum/views/page.rb, test/test_app.rb, test/test_page_view.rb
* Implement command line switch `--no-display-metadata` to disable metadata rendering globally (enabled by default)
* Implement `rendered_metadata` method in the `Page` view
* Updated `page` layout and CSS to render metadata tables
* Added a test
This will fail until we release `gollum-lib 5.0.a1` and make `gollum` depend on that. However, the tests already pass locally.
Metadata tables render prettily for simple `{:key => :value}` metadata...
...but also for more complicated metadata with iterated hashes and arrays:
The latter overflows the table and makes it scrollable (so too large tables will not run off the edge of the page).
=> Yaml frontmatter

lib/gollum/app.rb, lib/gollum/helpers.rb, lib/gollum/templates/layout.mustache, test/test_app.rb, test/test_unicode.rb
Refactor front end to deal with lack of whitespace substitution and the end of file extension suppression in `gollum-lib`.
=> Remove ws subs

lib/gollum/public/gollum/javascript/editor/gollum.editor.js
Keyboard shortcut dialog is a long-missing feature as indicated by #505. With the ace editor, we can easily add one. This PR implements that using the standard code from https://ace.c9.io/demo/keyboard_shortcuts.html.
Global shortcuts like `Ctrl-s` does not work on the editor area in 5.x since ace editor seems to grab all keyboard events. This can be addressed by the same approach. This PR add `Ctrl-s` back in the editor area.
=> Add keyboard shortcuts dialog. Closes #505.

lib/gollum/app.rb, lib/gollum/views/create.rb, lib/gollum/views/edit.rb
The views were still substituting '-' with space, causing problems when trying to edit pages containing '-'.
I now searched the repo for instances of the string `'-'` and `"-"`, which should return any cases of attempted ws substitution in ruby or javascript (unless I'm too unimaginative). The only other hit was the instance in `app.rb`, which I also took care of in this PR.
=> Found more spurious whitespace substitution.

gollum.gemspec, lib/gollum.rb
Change gollum version to 5.0.1b to prevent confusion during development. Closes #1278.
=> Change gollum version to 5.0.1b to prevent confusion during development. Closes #1278.

lib/gollum/public/gollum/javascript/editor/gollum.editor.js
When files are uploaded to the editor using drag-and-drop, they are given this tag:
```
[[/path/to/file.ext]]
```
If the file is an image it is displayed correctly, otherwise a broken image link is shown. This pull request checks creates an alternative tag showing the file name if the file is not an image:
```
[[file.ext|/path/to/file.ext]]
```
```
**current behaviour**  
[[/Home/document.pdf]]
```
```
**proposed behaviour**  
[[document.pdf|/Home/document.pdf]]
```
=> Handle non-image uploads correctly

lib/gollum/public/gollum/javascript/gollum.js.erb, lib/gollum/public/gollum/stylesheets/template.scss, lib/gollum/templates/page.mustache, lib/gollum/views/page.rb, test/test_page_view.rb
Use YAML frontmatter to enable header counting via CSS:
```
---
countheads: true
---
```
Result:
But it is also possible to specify another counter style (also e.g. roman numerals, see `VALID_COUNTER_STYLES` in `page.rb`):
```
---
countheads: 'tibetan'
---
```
Result:
=> Implement header counting using YAML frontmatter. Resolves #908

lib/gollum/app.rb
base_url is being determined from the rack environment, and is encoded in ascii-8bit. We want all data entering the app to be utf-8 encoded.
=> Fix encoding for base_url app.rb. Resolves #1339

bin/gollum, lib/gollum/app.rb, lib/gollum/assets.rb, lib/gollum/public/gollum/javascript/editor/langs/asciidoc.js, lib/gollum/public/gollum/javascript/editor/langs/creole.js, lib/gollum/public/gollum/javascript/editor/langs/markdown.js, lib/gollum/public/gollum/javascript/editor/langs/org.js, lib/gollum/public/gollum/javascript/editor/langs/pod.js, lib/gollum/public/gollum/javascript/editor/langs/rdoc.js, lib/gollum/public/gollum/javascript/editor/langs/textile.js, lib/gollum/public/gollum/javascript/gollum.js.erb, lib/gollum/public/gollum/stylesheets/app.scss, lib/gollum/public/gollum/stylesheets/criticmarkup.scss, lib/gollum/public/gollum/stylesheets/editor.scss, lib/gollum/templates/editor.mustache, lib/gollum/templates/layout.mustache, lib/gollum/views/edit.rb, lib/gollum/views/layout.rb
This PR implements styling for CriticMarkup (backend support is already in gollum-lib: https://github.com/gollum/gollum-lib/pull/308). 
In addition, this PR also adds two buttons to the editor for accepting or rejecting proposed changes in selected text.
=> Implements frontend support for CriticMarkup. Related to #1016.

lib/gollum/app.rb, lib/gollum/public/gollum/javascript/gollum.js.erb, lib/gollum/templates/editor.mustache, lib/gollum/views/edit.rb, test/test_app.rb, test/test_unicode.rb
This PR implements the infrastructure for detecting and handling simultaneous edits. It does this on the basis of a hash of the contents of the page. The hash is generated in the `get 'edit/*'` action and passed into the `gollum-editor-form` form as a hidden field named `etag`. When, after editing the page, the form is submitted via an ajax call to `post 'edit/*'` the original hash is compared to a new hash of the contents of the page before the new changes are applied. If the hashes match, this means that the page has not been modified since the user started editing. If the hashes do not match, the page has been changed in the meantime, and action has to be taken to resolve the version conflict. In the current implementation, a conflict results in a notification warning the user about …
=> Implement infrastructure for detecting and handling simultaneous edits

lib/gollum/app.rb
Fairly straightforward fix since the relevant code will live in `gollum-lib`. Basically, the proposal is to add to class methods to `Gollum::File`, namely `image?(filename)` and `binary?(filename)`. Thoughts?
NB. This PR should not be merged until `gollum-lib-5.x` implements these methods.
=> Do not attempt to normalize uploaded files unless they have valid page extensions.

Rakefile, bin/gollum, lib/gollum/app.rb, lib/gollum/public/gollum/javascript/editor/gollum.editor.js.erb, lib/gollum/public/gollum/javascript/gollum.dialog.js.erb, lib/gollum/public/gollum/javascript/gollum.js.erb, lib/gollum/public/gollum/stylesheets/_base.scss, lib/gollum/templates/page.mustache, lib/gollum/views/helpers.rb, lib/gollum/views/pages.rb
Found a couple of instances where the javascript was not using path helpers. I did some extensive grepping, including for `'/`, `baseUrl`, and all the currently existing route names, and moved to using the path helpers.
=> Use path helpers consistently

lib/gollum/public/gollum/stylesheets/gollum.scss, lib/gollum/templates/create.mustache, lib/gollum/templates/edit.mustache, lib/gollum/templates/history.mustache, lib/gollum/templates/page.mustache, lib/gollum/templates/pages.mustache, lib/gollum/templates/search.mustache, lib/gollum/templates/searchbar.mustache
This PR fixes issue https://github.com/gollum/gollum/issues/920. In addition, it moves the Home button to the upper left corner for consistency between views.
=> Move page title (h1) down. Move Home button to upper left corner on all views.

lib/gollum/public/gollum/stylesheets/gollum.scss, lib/gollum/templates/page.mustache, lib/gollum/views/page.rb
Notice that this breadcrumb trail will currently include `page-file-dir` as an element when it is enabled. However, since `page-fir-dir` [is set to become internal](https://github.com/gollum/gollum/issues/1052), this should resolve itself once https://github.com/gollum/gollum/issues/1052 is implemented.
=> Implements a breadcrumb for normal wiki pages. Resolves #629.

lib/gollum/views/page.rb
h1-title cannot fetched H1 tag at org-mode.
It fixed.
ref: #1372
`H1 Title1` should be the page title.
```
$ bundle exec ./bin/gollum --versions
Gollum 5.0.1b
Running on: x86_64-darwin18 with Ruby version 2.5.3
Using:
gollum-grit_adapter 1.0.1
gollum-lib 5.0.a.4
rugged 0.28.1
gollum-rugged_adapter 0.4.4
With the following renderers:
kramdown 1.17.0
org-ruby 0.9.12
```
`H1 Title1` is the page title.
This is page content.
=> Fix h1-title at org-mode

lib/gollum/views/helpers.rb
We didn't catch this because the revert tests are disabled
=> Add revert route helper. Resolves #1385

gollum.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement. This PR removes that property.
* [RubyForge was closed down in 2013][1].
* [rubygems/rubygems#2436 deprecated the `rubyforge_project` property][2].
[1]: https://twitter.com/evanphx/status/399552820380053505
[2]: rubygems/rubygems#2436
=> Gemspec: drop EOL'd property rubyforge_project

lib/gollum/app.rb
Show subpages on preview page. They are rendered dynamically based on the content of the subpage textareas in the editor -- so it's an actual preview, rather than rendering the committed sidebar/header/footer!
Requires merge of https://github.com/gollum/gollum-lib/pull/333
Result:
=> Show subpages in preview

lib/gollum/public/gollum/javascript/editor/gollum.editor.js.erb, lib/gollum/templates/editor.mustache
Fix RTL button that broke in the Primer.css merge commit by changing the button's `id`.
=> Fix RTL button. Rename Edit Mode label to Markup.

lib/gollum/app.rb, lib/gollum/public/gollum/javascript/gollum.js.erb, lib/gollum/public/gollum/stylesheets/template.scss, lib/gollum/templates/history.mustache, lib/gollum/templates/history_authors/none.mustache, lib/gollum/templates/latest_changes.mustache, lib/gollum/templates/layout.mustache, lib/gollum/templates/pagination.mustache, lib/gollum/templates/wiki_content.mustache, lib/gollum/views/compare.rb, lib/gollum/views/has_page.rb, lib/gollum/views/history.rb, lib/gollum/views/latest_changes.rb, lib/gollum/views/overview.rb, lib/gollum/views/page.rb, lib/gollum/views/pagination.rb, test/test_app.rb, test/test_latest_changes_view.rb
Add pagination for the latest_changes and history views.
Results:
(There is only a 'Next' link on the first screenshot because it's the first page)
I also noticed that when you'd view an old version of a file (e.g. by getting `Bilbo-Baggins.md/59721c7d7ca4fa6a07a50d76b3b0c92adfb8c3db`) the 'Delete Page' and 'When was this page last edited?' links were still visible in the footer. On historical pages, I've replaced this with the following:
=> Pagination for history and latest changes.

lib/gollum/public/gollum/javascript/gollum.js.erb
Toggling the 'When was this page last edited?' link caused text in the footer to move upward. Fix.
=> Improve page-info-toggle JS

lib/gollum/public/gollum/javascript/app.js, lib/gollum/public/gollum/javascript/editor/gollum.editor.js, lib/gollum/public/gollum/javascript/editor/langs/asciidoc.js, lib/gollum/public/gollum/javascript/editor/langs/creole.js, lib/gollum/public/gollum/javascript/editor/langs/default.js, lib/gollum/public/gollum/javascript/editor/langs/markdown.js, lib/gollum/public/gollum/javascript/editor/langs/mediawiki.js, lib/gollum/public/gollum/javascript/editor/langs/org.js, lib/gollum/public/gollum/javascript/editor/langs/pod.js, lib/gollum/public/gollum/javascript/editor/langs/rdoc.js, lib/gollum/public/gollum/javascript/editor/langs/rest.js, lib/gollum/public/gollum/javascript/editor/langs/textile.js
Also fixes two bugs:
* `reStructuredText function buttons were not being activated because the language was called 'rest' rather than 'rst' (`rest.js`)
* function buttons were not being reset on switching language because the buttons are `<button>` elements rather than `<a>` elements since the move to Primer (`gollum.editor.js`)
=> DRY language definitions

lib/gollum/public/gollum/stylesheets/template.scss.erb
=> Add CSS for table.toc Fix #925

lib/gollum/app.rb, lib/gollum/helpers.rb, test/test_app.rb
The title of a preview page:
* Was unescaped, so filenames containing spaces had title e.g. "Samwise%20Gamgee"
* Included the page extension even when the URL didn't.
Solved with a minor change to the route in `app.rb`
=> Solve minor issue involving Preview title

lib/gollum/public/gollum/javascript/gollum.js.erb
Noticed two issues:
* editor was taking me to the wrong page when editing/saving a file in a subdirectory.
* this was because `newPath` was missing a leading slash when `pagePath` was not empty
* In the Overview, when clicking 'New' in a subdirectory, the dialog box would say 'This page will be created under //Mordor'
Luckily, both could be addressed by introducing a new JS helper method that ensures a leading slash is present.
=> Fix redirect location for editor submit

Rakefile
Precompiling currently throws the following error.
`NameError: uninitialized constant Gollum::Markup`
Not sure if this is the correct fix, but requiring gollum and
gollum-lib restores functionality.
=> Rake precompile: Add missing requires

lib/gollum/app.rb, lib/gollum/helpers.rb, lib/gollum/public/gollum/javascript/gollum.js.erb, test/test_allow_editing.rb, test/test_app.rb
This PR adds basic redirect support (#1023). Any time a rename action is successful, a redirect entry is added to the protected file `.redirects.gollum` via `wiki#add_redirect(old_path, new_path)`.
The redirects file is only queried as a last resort, when no page or file could be found.
When a redirect is found and is followed, the user is notified of this through a dismissable flash notification.
This PR also adds a helper `flashNotice(type, notice)` for adding flash notices to pages.
=> Add redirect support (e.g., after renames). Fixes #1023.

lib/gollum/public/gollum/javascript/gollum.js.erb
This PR adds visual feedback to successful uploads through the Upload button by showing a flash notice. The feedback for unsuccessful uploads is improved by also showing a flash notice instead of a JS alert.
This PR also improves the `flashNotice` helper in the following ways:
* flashNotice will replace an existing flash notice if one already exists.
* flashNotice will add an automatic fade-out to success notices. The fade-out will occur after 5 seconds.
* flashNotice now takes additional optional parameters to add an action button to the notice. This is currently unused, but may come in handy in the future. Example:
`flashNotice("warn", "Careful, you are about to ...", "Are you sure?", "alert('boo')", "danger")`
This will add a danger button to the flash notice with the label "Are you …
=> Show flashNotice instead of JS alert for (un)successful uploads.

lib/gollum/public/gollum/javascript/gollum.js.erb
The edit link for editing sections wasn't using the full path to the page.
=> Fix editable section link

lib/gollum/app.rb, lib/gollum/public/gollum/javascript/gollum.js.erb
The flashed notice for successful uploads had some weird behaviour that looks like it was added for debugging.
Upload commits would have an incorrect path (e.g. "Uploaded file to uploads/uploads/52514235_365861454017357_1956855208312945998_n.jpg") because `reponame` already contains `dir`.
=> 5.x: Fix a couple of upload issues

test/helper.rb
Previously, the test suite was broken for older git versions because git (e.g. version 2.14.3 (Apple Git-98)) could not clone to Tempfiles. This PR fixes the issue by cloning to a tmpdir instead of a Tempfile.
=> Use tmpdir instead of tempfile for creating temporary repos in the test suite.

Gemfile
We may also want to fix this in master, depending on when we think the 5.x release will be out.
=> Update rake to mitigate CVE-2020-8130.

lib/gollum/templates/wiki_content.mustache, lib/gollum/views/page.rb
This PR restores the functionality for programmatically determining the position of the sidebar (left or right).
The default position is `:right`. To change, set `wiki_options['sidebar'] = :left`. Or in config.rb:
```ruby
wiki_options = {sidebar: :left}
Precious::App.set(:wiki_options, wiki_options)
```
=> Restore functionality for determining the position of the sidebar (left or right).

HISTORY.md, README.md, bin/gollum, test/test_unicode.rb
I removed the Videos section from the Readme because the videos are all based on 4.x. Or is it better to have something rather than nothing here?
=> Remove more references to grit and start updating readme

README.md, bin/gollum, bin/gollum-migrate-tags, test/test_migrate.rb
Support the hyphenate option in the migration script, too. Will require minor changes after https://github.com/gollum/gollum-lib/pull/365 is merged.
=> Update migration script

HISTORY.md, README.md, bin/gollum
@bartkamphorst what do you think of adding the `--no-strict-tag-lookup` option as a combined option? We could also remove the individual options (they could still be set separately in a `config.rb`).
=> Add --lenient-tag-lookup option

lib/gollum/templates/navbar.mustache
`px-1` class has been replaced with `pl-1` so that the right edge of the `div#wiki-wrapper` is aligned.
Current:
This PR:
=> Remove a tiny padding in the head div

lib/gollum/public/gollum/stylesheets/template.scss.erb
We now use the same font sizes for H1-H6 as Github does:
=> Let Primer.CSS determine H1-H6 styling (fixes #1515).

lib/gollum/app.rb, test/test_app.rb
So that /history/wrong-name gets redirected to / successfully.
=> Check page.nil? before page.wiki

lib/gollum/app.rb
Because `redirect_to()` does not respect `base_path` while `redirect to()` does.
=> Replace redirect_to() with 'redirect to()`

lib/gollum/templates/overview.mustache
This correct the `data-file-path` attribute's value so that the value includes the ancestor directories to a file.
This is a fix for a bug that, for example, deleting `abc/def.md` actually deletes `def.md`.
=> Fix `data-file-path` in overview pages

Rakefile, lib/gollum/assets.rb
Leave JS human readable when running Gollum with `RACK_ENV=development`.
=> Don't uglify JS in development env

lib/gollum/templates/overview.mustache
Address the issue #1572 just by adding the missing double-quotes in an `<a>` tag.
=> Address the issue #1572

lib/gollum/app.rb, lib/gollum/templates/history.mustache, test/test_app.rb
First pass at letting compare work in non-edit mode - potential fix for #1546.
Based on comments in the issue, it made more sense for compare to be a get as nothing is changed on the server and this lets it past the forbidden check for POST requests. The routes have to be rearranged to allow the more specific regex to match the request before the general one accepts everything.
=> Let compare versions be used in no-edit mode 

lib/gollum/helpers.rb, lib/gollum/templates/layout.mustache, lib/gollum/templates/navbar.mustache, lib/gollum/templates/search.mustache, lib/gollum/views/has_page.rb, lib/gollum/views/helpers.rb, lib/gollum/views/layout.rb, lib/gollum/views/overview.rb, lib/gollum/views/page.rb, lib/gollum/views/search.rb
As proposed in #1555, `page_route()` and `clean_url()` have been enhanced and applied to replace raw `base_url`s in mustache templates and ruby sources.
There may be some more places to be refactored, but I want somebody to review the changes before it gets too difficult to track.
=> Reduce direct use of base_url

lib/gollum/templates/navbar.mustache
A trailing slash is added. This fixes the behavior when `base_url` is `nil`.
=> Address home button issue #1590

lib/gollum/templates/layout.mustache, lib/gollum/views/layout.rb
Caught another issue related to https://github.com/gollum/gollum/issues/1602. The layouts referenced the `mathjax_config` method, but this was by default being interpreted as an attribute accessor for the `@mathjax_config` instance variable -- not the method in `layout.rb` which transforms `@mathjax_config` using `page_route`. Renamed the latter method, and referenced the new method name in the layout template.
=> Fix mathjax config path

lib/gollum/app.rb, test/test_app.rb
Strangely, it seems that `params[:page]` is already escaped -- perhaps by Sinatra? When you inspect `params` when you get the page `/Samwise%20Gamgee.md`, `params[:page]` will already be `Samwise Gamgee.md`. The fact that we were calling unescape on the already escaped string caused #1615: "C++.md" was being escaped into "C  .md".
=> Don't escape page path. Resolves #1615

bin/gollum, lib/gollum.rb, lib/gollum/app.rb
This is a proposed solution to the question in #1603 . Basically, we just allow users to create a `Gollum::TemplateFilter` in their `config.rb` and let them manipulate the contents of `_Template` however they want at runtime. What do you think about this approach @dometto? A very simple example of such a filter could be the following:
```ruby
module Gollum
class TemplateFilter
def self.filter(data)
return data.gsub!('{{current_date}}', Time.now.strftime("%d/%m/%Y"))
end
end
end
```
(Where `_Template.md` would obviously need to include something like `Date: {{current_date}}`.)
=> Filter _Template content. Resolves #1603 and #1640.

CONTRIBUTING.md
The CONTRIBUTING document referenced a file that has since been moved.
=> Update reference to test git bare repositories

lib/gollum/templates/wiki_content.mustache, lib/gollum/views/page.rb, test/test_page_view.rb
Gollum's sidebar did not render very well for me on my mobile device. Using Primer CSS utilities, I was able to make a mobile-friendly grid with minimal changes.
Please see the individual commit messages for more details rationale for each change.
Here's a screenshot of the (unchanged) desktop layout resulting from these commits:
And here's a screenshot of the mobile layout with a sidebar and footer enabled:
=> Make sidebar layout mobile-friendly

lib/gollum/views/overview.rb, lib/gollum/views/page.rb, test/test_overview_view.rb, test/test_page_view.rb
These commits respond to a bug reported, #1658.
In investigating the bug, I found opportunities to add additional tests around retaining and displaying unicode characters. See the commit messages for more detailed information.
=> Only escape HTML from breadcrumbs. Resolves #1658

lib/gollum/templates/wiki_content.mustache
Resolves #1674.
@dometto reported that there was no spacing between the optional sidebar and footer containers. This would look a bit funny in edge cases, specifically if the sidebar was longer than the main wiki content or both the main wiki content and the sidebar were empty.
After:
While investigating the above issue, I noticed that the footer and sidebar also had very different content padding definitions, which looked off on mobile devices--though I think it is technically off on all devices.
You can see the padding change in the above screenshot, but it's much clearer on mobile:
Before:
After:
=> Fix sidebar and footer padding

lib/gollum/templates/editor.mustache
**EDIT**: oops, accidentally included the same screenshot twice. Now fixed!
Looks like the update to Primer caused the Markup and Keybinding select elements in the editor view to become larger than they were:
This PR makes them smaller again so they fit on the same row:
But as you can see there is not much space between these fields and the buttons to the left. Is this acceptable styling, or should we e.g. move the selects down a row?
=> Make Keybinding and Markup selects smaller

lib/gollum/templates/latest_changes.mustache
This brings the flexbox on the latest changes view in line with that on the page history view, which also has `col-5` rather than `col-7`.
Before:
After:
=> Fix styling for Latest Changes flexbox

lib/gollum/views/compare.rb, test/test_compare.rb
Was getting an error on JRuby when comparing a rename commit in the Latest Changes or Page History views. It turns out JGit handles rename commits slightly differently from Rugged.
Here's `diff` and `lines_to_compare` on MRI:
```ruby
"diff --git a/Bar.md b/Bar.md\nnew file mode 100644\nindex 0000000..e69de29\n--- /dev/null\n+++ b/Bar.md\n"
["--- /dev/null", "+++ b/Bar.md"]
"diff --git a/Foo.md b/Foo.md\ndeleted file mode 100644\nindex e69de29..0000000\n--- a/Foo.md\n+++ /dev/null"
["--- a/Foo.md", "+++ /dev/null"]
```
And here on JRuby:
```ruby
"diff --git a/Foo.md b/Bar.md\nsimilarity index 100%\nrename from Foo.md\nrename to Bar.md"
["rename to Bar.md"]
```
This PR makes sure diffs consisting of JGit-style rename lines are appropriately skipped by the `compare.rb` view. @bartkamphorst …
=> Fix jruby compare rename

lib/gollum/templates/editor.mustache
Noticed the image button icon was weirdly out of style compared to the other editor buttons! Using a different octicon helped.
Before:
After:
=> Update image icon in editor

lib/gollum/templates/navbar.mustache
If the user has edit permissions, the "History" button is shown in a button group with "Edit" and "Rename". If the user does not have edit permissions, it's shown by itself.
This is a small change, but it seems more semantic to me: All of the "Edit", "Rename", "Upload" and "History" buttons should be displayed in the same button group because they are all actions that relate to the current page. All other buttons ("New", "Overview", "Latest Changes") do not.
This commit also renames the label from "Page History" to "History".
=> Move "Page History" into button group

lib/gollum/templates/navbar.mustache
Fixes #1692.
There was a display issue, where navbar items's outline styles were being cut off due to the parent `<nav>` element's margin and padding.
Fortunately, we can do away with the navbar wrapper div entirely. It was not doing anything important except defining its children as `TableObject` items. But we can just do this on the `<nav>` itself.
=> Fix nav outline styles

lib/gollum.rb
DublicatePageError is definded in both gollum and gollum-lib. They don't have the same arguments, which causes an error when we raise the exception when gollum is required. The fix is just removing the exception from gollum while leaving it in gollum-lib.
=> Delete dublicate DublicatePageError error

lib/gollum/views/page.rb, test/test_page_view.rb
Fixes #1709.
I made a mistake when I made `#title` a private method. I did not see
that it was being called from `layout.mustache` to generate the
`<title></title>` tag in the `<head></head>` of each page.
This fixes my error, and adds tests so the behaviour is more explicit.
=> Ensure <title> is rendered for pages

.travis.yml
Our JRuby CI runs have been errorring due to what I think is an issue with an older `jruby-openssl` version.
=> Use recent JRuby release for Travis CI

.github/workflows/test.yaml, .gitignore, .travis.yml, README.md, test/test_migrate.rb
- This is to switch from Travis CI which is shutting down the org version,
and the .com version, a free account is limited.
- Switch test environment variable from TRAVIS to CI to be more generic.
=> fixes #1723: Github Actions Supported

lib/gollum/app.rb
**Note:** This error also picked up various whitespace issues from the committed
file. While technically unrelated to this change, I'm just leaving the whitespace
fixes in here.
An issue was reported (see #1721) where, in docker containers where the
`LANG` was not being set, `Precious::App` would serve Mustache templates
in an ASCII encoding. This caused templates to error out.
In the past, this would have happened in environments where `LANG` was
not set and the Gollum applciation configuration had enabled MathJax.
Now, it happens even if MathJax is disabled because of a UTF-8 character
I added to the mobile navigation menu.
Basically, we should enforce a UTF-8 encoding from now on to avoid
runtime errors related to ASCII encoding.
=> Explicitly set encoding for `Precious::App`. Resolves #1721

bin/gollum
Exit with code 1 (error) when invalid option is given (as is standard for unix programs).
=> Update gollum launch script

.github/workflows/docker-test.yml, Dockerfile, docker-run.sh
This change reduces the size of the Docker image from 446 MB to 126 MB (-71%). This can be tested using the public [`rgov/gollum`](https://hub.docker.com/repository/docker/rgov/gollum) image.
The new image also makes it possible to pass arguments to the `gollum` process (e.g., `docker run gollumorg/gollum --config=...`). Previously the image only passed `--mathjax`. (**Note:** After applying this change, users will have to explicitly pass `--mathjax`.)
The smaller image image is based on Alpine Linux instead of Debian Bullseye. It also uses a separate build stage for compiling and installing the gem dependencies, which are then copied over to the final image.
I tested the new image by browsing an existing wiki, creating a new page, editing it, previewing the edits, and uploading a file. …
=> Reduce size of container image

.github/workflows/test.yaml, Gemfile, gollum.gemspec
No longer needed after nokogiri's recent release, see https://github.com/gollum/gollum/issues/1779
=> Remove explicit nokogori version requirement. Resolves #1779

.github/workflows/docker-deploy.yml
This PR
1. Also builds/deploys the Docker image on new releases, not just on pushes
2. Conditionally sets the DockerHub tag to either `master` in case of a push or the tag name (e.g. `v5.2.3`) in case of a release
I have stopped using the label `latest` because many seem to recommend against using that label, since it is confusing: https://vsupalov.com/docker-latest-tag/
Specifically, in our case, it could be understood to refer to the lastest *stable* version. But `master` is sometimes not stable (for instance when we add features that also require changes to gollum-lib). I think using the tag `master` for the Docker image is more descriptive, but open to other suggestions! (Could also be e.g. `nightly-2021-01-11`, etc.)
=> Support versioned Docker builds

Rakefile, gollum.gemspec
RubyGems says not to set the value to `date`, `specification_version` and `rubygems_version`.
https://github.com/rubygems/rubygems/blob/fe96fb6e2ac5a8b6df5e852470d11fa854301eca/lib/rubygems/specification.rb#L1677-L1682
https://github.com/rubygems/rubygems/blob/fe96fb6e2ac5a8b6df5e852470d11fa854301eca/lib/rubygems/specification.rb#L750-L755
https://github.com/rubygems/rubygems/blob/fe96fb6e2ac5a8b6df5e852470d11fa854301eca/lib/rubygems/specification.rb#L536-L541
This PR removes those fields from gemspec.
And does the following:
- Fix gemspec task not to set date field.
- Remove unused codes related with rubyforge_project from gemspec task.
=> Remove fields from gemspec that should not be set

.github/workflows/test.yaml
This PR adds Ruby 3.1 to the CI matrix.
And enclose 3.0 in quotes to ensure that Ruby 3.0 is used correctly.
Please see https://github.com/ruby/setup-ruby/issues/252 for more details.
=> Add Ruby 3.1 to the CI matrix

lib/gollum.rb, lib/gollum/app.rb, test/test_app.rb
The PR #1612 is a great start to resolve #1603, it introduced the template filter.
This one is a step forward to allow accessing more context (namely `page.name`) in a template filter, as described here:  https://github.com/gollum/gollum/pull/1612#discussion_r826596006
=> Add page context to template filter, resolves #1603

gollum.gemspec
We've had some reports (#1342, #1809) of `rdoc` not being installed in some environments, causing Gollum to error in unpleasant ways.
This isn't an issue that's unique to Gollum, and I don't think `rdoc` should actually be a hard dependency of this project.  But since we can side-step the issue by requiring `rdoc`, something that most users who install Gollum via RubyGems would already have installed, I don't think this is a horrible solution.
=> Include `rdoc` as a dependency

lib/gollum/app.rb, lib/gollum/helpers.rb, test/test_app.rb, test/test_app_helpers.rb
This PR fixes #1830 and attempts to make the logic for generating the correct upload location for the "per page" upload mode more robust.
We generate the upload location from `request.referer` in the `upload_file` route. #1830 was caused because of a mistake in the regular expression trying to match the `base_url` part in the referer: we were not expecting it to start with a slash.
Investigation also revealed another, similar problem: we were also not handling referers containing `/gollum/foo` at the start of the URL. Again, our regex was expecting a slash at the beginning, whereas that leading slash was already removed earlier in the method.
These two problems were not caught by the tests because we were not testing these two cases:
1. The case in which the referer contains `/gollum/foo` …
=> Refactor logic for determining per page upload location. Resolves #1830

Gemfile, Rakefile, test/helper.rb, test/integration/test_js_errors.rb
Thought it might be desirable to have integretion/acceptance tests to prevent bugs like #1704. This uses capybara to make sure no JS errors (or actually: no unexpected errors) are thrown. In the future, we could also add more demanding tests for gollum's frontend (e.g. to make sure an update to ACE or other JS assets don't break the editor).
@benjaminwil @bartkamphorst do you think tests like these are desirable? If so, do we want to get them to work on travis, or just run them locally?
=> Add integration tests with capybara

lib/gollum/views/rss.rb, test/test_app.rb, test/test_rss_view.rb
Resolves #1815
In issue https://github.com/gollum/gollum/issues/1815, it was reported that Gollum RSS feeds attempt to put entire commit messages into a feed item's `<title>` element.
Given that commit messages can be many paragraphs long, this is not an acceptable way to render a feed item title.
If a commit has many lines or paragraphs, we now put those inside the `<description>` element as of this commit.
While I was editing this view, I decided it would be a good time to increase test coverage, as this view renderer was not under test at all. I also fixed a typo ("Commited" should say "Committed"). There are implicit dependencies on other gems that provide the
`Gollum::Git::Commit`, `Gollum::Git::Actor`, and `Rugged::Commit` classes here, so mocking out simple versions of their …
=> Refactor RSS view renderer

README.md
I can't find any evidence that we currently use SauceLabs for testing. Happy to close this if I'm wrong.
=> Remove link to SauceLabs

lib/gollum/templates/wiki_content.mustache, test/capybara_helper.rb, test/integration/test_app.rb, test/integration/test_js_errors.rb
Resolves #1851
Since we're passing the path to our ajax route as `data` using JQuery, it is already auto-encoded. We hence don't need to use `escaped_url_path`, but can simply use `path`. (Note: since we're using mustache's `{{ }}` to print `{{path}}`, this is aready html-escaped.)
=> Don't double escape url for the last modified info link

lib/gollum/templates/search.mustache, lib/gollum/views/search.rb, test/integration/test_search.rb
Resolves #1873. 
An issue was reported (in discussion #1872) that search terms with special characters (specifically `#`) were resulting in URLs that did not lead to any search results where there should be search results.
I was able to reproduce this issue in a feature test and fix it in the view class.
=> Ensure search terms in URLs are escaped

lib/gollum/public/gollum/stylesheets/template.scss.erb
This PR resolves #1693 by adding rounded corners to gollum's tables.
=> Add rounded corners to tables. Resolves #1693.

lib/gollum/templates/searchbar.mustache
I just noticed that gollum's search bar was not neatly aligned with the navigation buttons.
This PR fixes this by giving the search input the class "input-sm".
=> Resize searchbar to match navigation buttons.

docker-run.sh
Hi,
Things go sideways if you're trying to use a bare repository and a docker container and I believe this change will fix it.
Creating an empty .git directory is another workaround.
=> Make docker-run.sh work if you're in a bare git repository

bin/gollum, gollum.gemspec, lib/gollum/assets.rb
As described in #1909, we only use the `uglifier` gem when generating the packaged assets. This PR moves it to the development dependencies.
Additionally, I have added the ability to specify a custom location for the `node_modules` directory when using the `--development-assets` option.
=> Remove uglifier. Resolves #1909

lib/gollum/app.rb
Resolves #1766
* Renames the `#commit_message` method to the more accurate `#commit_options` (since it already returns author data in addition to the message)
* Adds a `:notes` key to the  hash returned by `#commit_options`, the value of which is sourced from the session
* the relevant session key (`gollum.notes`) can be set by a piece of middleware, analogous to the way this works for author info
Possible use cases are e.g. getting the client IP and using this info in the `:post_commit` Hook. In the future, we could provide a feature to actually store the contents of the `:notes` field in a [git note](https://git-scm.com/docs/git-notes). For now, this only passes the info on to the `Committer` object. https://github.com/gollum/gollum-lib/pull/431 ensures the note is stored in the …
=> Allow setting notes in commit_options from session data

README.md
Our [CuttingEdge](https://github.com/repotag/cutting_edge) instance at Heroku is gone, update the Readme to point to the new instance hosted on Render.
=> Update link to CuttingEdge in Readme

lib/gollum/views/page.rb
The `Page` view was setting its own xml conversion options rather than using the identical settings from `gollum-lib`.
I came across this while trying to fix a nokogiri error in JRuby. See https://github.com/sparklemotion/nokogiri/issues/2761 for context.
=> Use to_xml defaults from gollum-lib

lib/gollum/views/page.rb
The `content` method is being re-defined below.
=> page.rb: remove unnecessary attr_reader

test/test_app.rb
This test failed on JRuby recently because of a change in behaviour to nokogiri. It took me quite a while to figure out what exactly was broken because it seemed like there might be an ut8 issue, but really the test was only failing because it's trying to strictly match whitespace, and the exact whitespace used by nokogiri had changed. I've rewritten the test to be more robust.
Note: we still have a test guarding against wrong use of whitespace in  https://github.com/gollum/gollum/blob/master/test/test_app.rb#L22.
=> Improve utf-8 test

.github/workflows/docker-test.yml, .github/workflows/test.yaml, gollum.gemspec, lib/gollum/app.rb, lib/gollum/views/layout.rb, lib/gollum/views/template_cascade.rb
The `mustache-sinatra` gem just received a bump release, which now utillizes the latest `mustache`. Unfortunately, this has suddenly exposed `gollum` to breaking changes in the latest `mustache`. I found two:
Error: `NoMethodError private method escape called for <<Precious::Views::Create: ...`.
**Diagnosis**:  in the latest `mustache`, views are expected to have an `escape` instead of an `escapeHTML` method. We were using the `escapeHTML` method provided by the `Rack::Utils` modules. By including that module, we also include a private `#escape` method, which mustache is now attempting to call.
**Fix**: instead of including `Rack::Utils`, just use the default `Mustache#escape`, which uses `CGI.escapeHTML`. Overriding the `#escape` method is only necessary for providing custom (non-HTML) …
=> Fix mustache

Rakefile
When doing backport releases recently, I ran into the problem that our `Rakefile` will only perform releases from branch `master`.  Having to do the releases manually led to user error on my part:
https://github.com/gollum/gollum/issues/1964
This PR allows more flexibility: if you explicitly run rake with the `RELEASE_BRANCH=` ENV variable, and you are on the relevant branch, everything will work smoothly.
=> Allow non-default release branch. Resolves #1964

Dockerfile, LATEST_CHANGES.md
Add the openssh alpine package to the docker image to allow ssh connected git repositories.
Issue: https://github.com/gollum/gollum/issues/1981
=> Add openssh client to docker image.

.github/workflows/docker-test.yml, .github/workflows/test.yaml, Gemfile, gollum.gemspec, lib/gollum/app.rb, lib/gollum/public/gollum/javascript/gollum.js.erb, lib/gollum/public/gollum/stylesheets/_base.scss, lib/gollum/public/gollum/stylesheets/template.scss.erb, test/helper.rb
This PR accompanies https://github.com/gollum/gollum-lib/pull/441, which eliminates the octicons gem from gollum-lib. This PR ensures that
* `Warn` and `Note` macros are styled with a default Octicon using a `::before` pseudo-element;
* Icon and Flash macros are styled with an Octicon of the user's choice. 
The latter works through jQuery html injection and a new `octicon` route, which uses the existing `OcticonHelpers` to lookup and prepare the appropriate octicon svg. 
If a requested icon name is not available, a broken img link is inserted instead (with a helpful `title`), to signal to the user that something went wrong.
Open issues:
@benjaminwil Any suggestions on how to improve the alignment with the text?
=> Style Note and Warn macros and inject requested Octicon icons for Flash and Icon macros.

lib/gollum/app.rb, lib/gollum/helpers.rb
This PR resolves #1979 by ensuring that slashes in redirect paths are not encoded. For the future, a more systematic approach might be desired, such as using the [addressable](https://github.com/sporkmonger/addressable) gem for encoding URIs while preserving slashes.
=> Do not encode slashes in redirects. Resolves #1979 .

lib/gollum/public/gollum/javascript/editor/gollum.editor.js
This PR resolves #1953 . 
Turns out that dragging and dropping of text is allowed by Ace out of the box. So our custom code to handle drag and drop file uploads was interfering with that feature, causing the `500` return status and corresponding message. The proposed fix is to check whether the dropped object is a File. If it isn't, then the code will return and let Ace do its thing (i.e. drop the dragged text into the editor).
=> When uploads are allowed, do not interfere with dragging and dropping of text in Ace editor. Resolves #1953.

.github/workflows/docker-deploy.yml, .github/workflows/docker-test.yml, .github/workflows/test.yaml
Resolves #1948
This PR utilizes path filters to prevent jobs from running when the affected files in a PR or push *all* match the filters. So if only a combination of .md or .txt files are committed, the job does not run. The purpose of this is a) to not lose valuable time waiting for lights to turn green when this is not necessary 😃 and b) not to publish images to Dockerhub unnecessarily. (At this point, when we update the Readme, a new image is published and it looks like everyone's image is out of date.)
This PR enables this behavior for:
* testing
* docker build testing
* deploying the docker image
Please sanity check whether this is what we want, and whether there are any other significant path patterns tht we should exclude.
Unfortunately it looks like [there is no way to reuse the …
=> Don't run jobs on trivial changes

lib/gollum/app.rb, lib/gollum/public/gollum/javascript/gollum.js.erb, test/test_app.rb
A `DuplicatePageError` is thrown when attempting to change the file extension of an exiting page to that of another already exististing page. That is, when: 
* A.md exists
* A.txt exists
* And we attempt to rename A.txt to A.md in the editor
This PR handles the resulting exception gracefully and returns a `409` in that case. It also ensures the error message is shown in the dialog that is triggered when pressing 'Save'
=> Handle 409 gracefully

Dockerfile, LATEST_CHANGES.md
Adds a `.gitconfig` containing the proper setting for `safe.directory` to allow the container user to load git configs under the `/wiki` directory. 
Fixes #2006
=> Add git configuration to Docker image

CONTRIBUTING.md
In 2023, not all git users have `init.defaultbranch` set to `master` anymore, which causes the Gollum test suite to fail. We can work around this with the instructions in the commit body.
This relates to #2007.
=> Add to development environment setup instructions

.github/workflows/test.yaml
The JRuby build that our CI pipeline uses comes from [`ruby/ruby-builder`][^1]. The Ruby version specified in our CI configuration was 9.4.3.0, which hasn't been rebuilt and re-released on `ruby/ruby-builder` since June 2023. Since October 2023, CI runs fail because of an issue with Psych 5.1.1[^2]:
NameError: cannot load (ext) (org.jruby.ext.psych.PsychLibrary)
org/jruby/ext/jruby/JRubyUtilLibrary.java:219:in `load_ext'
/home/runner/work/gollum/gollum/vendor/bundle/jruby/3.1.0/gems/psych-5.1.1-java/lib/psych.rb:7:in `<main>'
org/jruby/RubyKernel.java:1071:in `require'
/home/runner/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85:in `require'
/home/runner/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/rubygems.rb:610:in `load_yaml' …
=> Fix JRuby CI runs

lib/gollum/locales/en.yml, lib/gollum/templates/edit.mustache, test/capybara_helper.rb, test/integration/test_editor.rb, test/integration/test_page.rb
This small change started to localize the "edit" view partial.
While I was looking at this partial I realized that a) it was indented in an unconventional way and b) its buttons had `href` attributes, which is not something that `<button>`s have in valid HTML documents.
=> Improve and localize the "edit" view partial

.github/workflows/docker-deploy.yml
Append docker semver support to using like:
```bash
docker pull gollumwiki/gollum
docker pull gollumwiki/gollum:latest
docker pull gollumwiki/gollum:5.3.2         # Concrete version
docker pull gollumwiki/gollum:5.3           # Concrete minor version with latest hotfixes
docker pull gollumwiki/gollum:5             # Concrete major version with latest minor updates and hotfixes
docker pull gollumwiki/gollum:db4adc2       # Concrete commit
docker pull ghcr.io/gollum/gollum:5.3       # Use GitHub Container Registry as alternative registry
```
=> Docker semver supports

.github/workflows/docker-deploy.yml
Fix for gollum/gollum#2032
I apologize for the wait and the mistake I made in the previous PR.
[docker/metadata-action@v5](https://github.com/docker/metadata-action/tree/v5) can't handle `release` trigger, but works with `tags` trigger that are fire when created release.
Now the deployment is configured according to the following scheme:
- when push to `master`, creating images with tags `master` and `sha-{sha}`
- when push tags, creating images with tags `master`, `sha-{sha}`, `latest` and all semver variants 
---
> [!IMPORTANT]  
> Please create hotfix release `5.3.3` after merge PR for generating semver tags for image
> Otherwise only the `master` and `sha` tags will be created
=> Fix: GitHub Actions trigger for docker-deploy workflow

LATEST_CHANGES.md, README.md, bin/gollum, test/helper.rb
Say goodbye for the often misused `RACK_ENV` in favour of `APP_ENV` (like Sinatra does). A deprecation warning is printed if only `RACK_ENV` is set and Golllum has not yet reached version 6.
Related issue: #2029
=> Deprecate RACK_ENV in favour of APP_ENV

LATEST_CHANGES.md, lib/gollum.rb, lib/gollum/locales/cn.yml, lib/gollum/locales/en.yml, lib/gollum/templates/compare.mustache, lib/gollum/templates/create.mustache, lib/gollum/templates/editor.mustache, lib/gollum/templates/history.mustache, lib/gollum/templates/navbar.mustache, lib/gollum/templates/overview.mustache, lib/gollum/templates/search.mustache, lib/gollum/templates/searchbar.mustache, lib/gollum/templates/wiki_content.mustache, test/gollum/views/test_locale_helper.rb, test/integration/test_localization.rb, test/support/locales/cn.yml
This patch can support more languages, such as chinese.
```ruby
::I18n.default_locale = :cn
```
You just need to add a new line in the configuration to achieve the following effect.
I have added more content in the locales(gollum/lib/gollum/locales) to achieve better results.
I hope more people can contribute their mother tongue.
=> Support for more languages: chinese

LATEST_CHANGES.md, bin/gollum
Bug fix: Setting base_path in the config file didn't have any effect.
The config file was being loaded, but it wasn't being used to update the wiki_options local variable, so the config file wasn't affecting the base_path.
This change updates the wiki_options local variable after the config file is read. Now, the base_path can be set using the config file.
=> Re-read base_path after loading config file

.github/workflows/docker-test.yml, .github/workflows/test.yaml, lib/gollum/app.rb
Resolves #2050.
As reported in #2050 setting `base_path: /wiki` doesn't work, while `base_path: wiki` does work. It appears this is because the `MapGollum` class is setting the base route to `/#{base_path}`, so when passing in `/wiki`, the actual route being served is `//wiki`, not `/wiki`. By contrast, setting `--base-path /wiki` on the commandline works because the leading slash is being stripped [here[(https://github.com/gollum/gollum/blob/master/bin/gollum#L76C1-L77C1).
This PR attempts to solve the issue by handling extra slashes in the `MapGollum` class.
=> fix: MapGollum should handle superfluous slashes in base_path

bin/gollum, gollum.gemspec
Resolves #2059.
In `/bin/gollum` we try to instantiate the `Rack::Server` class, but it turns out [that class has been moved](https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#binrackup-rackserver-rackhandlerand--racklobster-were-moved-to-a-separate-gem) to a different gem (`rackup`, which we already depend on).
=> fix #2059: Rack::Server class has moved to the rackup gem

CONTRIBUTING.md, lib/gollum/app.rb
Resolves #2049.
@benjaminwil I tried to implement your suggestion of logging whether static assets are being used, but if I add a `puts` statement [here](https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L141) it displays on every page load.
We could alternatively do the same check (`wiki_options.fetch(:static, settings.environment != :gollum_development)`) in `bin/gollum`, but that duplicates that line. Additionally, adding a warning in `bin/gollum` would not produce the warning when running gollum with a `config.ru`. Do you have any suggestions, or shall we just leave it like this?
=> Use static assets when APP_ENV is development.

.github/workflows/release.yml, .github/workflows/test.yaml
The GitHub Actions "Create Release" workflow failed to build the JRuby release for Gollum v6.0.1.
This is a bit confusing to me, since the release step failed to pass the test run (`bundle exec rake`), which was passing as part of the "Ruby Build" workflow. The only difference I've noticed between the two workflow configurations was the version of Bundler used.
```
Run bundle exec rake
bundle exec rake
shell: /usr/bin/bash -e {0}
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
/home/runner/.rubies/jruby-9.4.0.0/bin/jruby -I"lib:lib:test:." /home/runner/work/gollum/gollum/vendor/bundle/jruby/3.1.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb "test/gollum/views/test_locale_helper.rb" "test/test_allow_editing.rb" "test/test_app.rb" "test/test_app_helpers.rb" …
```
=> Fix failing JRuby CI workflow

LATEST_CHANGES.md, bin/gollum
Fixing a small typo in the deprecation message for the command line option `--mathjax`. The message states to use `--math matjax`, which is mis-spelled and should be `--math mathjax`.
=> Mathjax deprecation typo

.github/workflows/docker-test.yml
There appears to be a new issue with the "Run gollum from Docker" step of the Build and Test Docker CI workflow.
Example of step failing:
```
git clone test/examples/lotr.git /tmp/lotr.git
RUNNER_TRACKING_ID="" docker run --user $(id -u) --rm -p 4567:4567 -v /tmp/lotr.git:/wiki -e CI=true gollum-ci-img --math katex &
sleep 10
netstat -lt
shell: /usr/bin/bash -e {0}
env:
CI_IMAGE: gollum-ci-img
Cloning into '/tmp/lotr.git'...
done.
To set a custom configuration for katex please add it to 'math.config.js' and commit it to the repo.
/usr/local/bundle/gems/rackup-2.2.1/lib/rackup/handler.rb:81:in `pick': Couldn't find handler for: puma, falcon, thin. (LoadError)
from /usr/local/bundle/gems/sinatra-4.1.0/lib/sinatra/base.rb:1627:in `run!'
from …
```
=> Resolve "Build and Test Docker" CI failures

.github/workflows/test.yaml, Gemfile, LATEST_CHANGES.md, test/test_app.rb
This pull request collects some changes to make JRuby CI runs pass. (I may throw in some other CI quality-of-life improvements.)
There is currently an issue in JRuby 9.4.9.0 because of the open-ended version requirement of `jar-depedencies` in the `psych` gem. The issue results in Gollum and its test suite being completely broken with this `Gem::LoadError`:
```
Gem::LoadError: You have already activated jar-dependencies 0.4.1,
but your Gemfile requires jar-dependencies 0.5.1. Since 
jar-dependencies is a default gem, you can either remove your
dependency on it or try updating to a newer version of bundler
that supports jar-dependencies as a default gem.
```
The issue is discussed here: https://github.com/jruby/jruby/issues/8488
And it will be resolved when 9.4.10.0 is released.
If your …
=> Resolve JRuby CI failures

LATEST_CHANGES.md, docker-run.sh
1. Please clearly explain the purpose of your PR. Let us know if it introduces a new feature, an enhancement, or fixes a bug.
Enhancement Proposal:
For docker images starting with 6.0 a non-root user needs the correct permissions to the mapped host volume:
`-v /path/to/git/directory/on/host:wiki`. If these are not set correctly, the docker container will continue to run, but the web page will not work.
This introduces a short check at the beginning of docker-run.sh to check for existence and writeability of the volume. If true, continue with the script, if false, exit. For both conditions issue a message describing success or failure.
2. Please link any issues that your PR addresses.
Inspired by #2084
3. If your PR changes any of the CSS or JavaScript under `lib/gollum/public`, don't …
=> Introduce directory permission check to docker-run.sh script (#2084)

Dockerfile
Our build-and-test GitHub Action raised warnings about these environment variables:
UndefinedVar: Usage of undefined variable '$UID'
More info: https://docs.docker.com/go/dockerfile/rule/undefined-var/
After readings about `ARG` more, it appears our Dockerfile was using it incorrectly[^1]:
An ARG instruction can optionally include a default value:
FROM busybox
ARG user1=someuser
ARG buildno=1
If an ARG instruction has a default value and if there is no value
passed at build-time, the builder uses the default.
This commit resolves the issues.
[^1]: https://docs.docker.com/reference/dockerfile/#arg
=> Resolve Dockerfile warnings re: $UID, $GID

Dockerfile
Update the version of ruby used in the docker image from `3.1` to `3.3`. We are already testing Gollum against 3.3, so this should be fine, and potentially improve performance a bit.
=> Update Ruby in Dockerfile

.github/workflows/release.yml
Resolves #2091
This PR resolves the problem that `gollum.war` was no longer being built automatically on a new release. I've also added some updates and a feature, since I was editing and testing the workflow file anyway:
* explicitly set `bundler` version. Using https://github.com/nektos/act to test the worklow locally, I noticed that `bundler 2.3` was being used. Locally, I had `bundler 2.5`, and with that version I managed to build the .war successfully.
* Update actions `ruby/setup-ruby` and `softprops/action-gh-release` to their latest versions
* Update to the latest version of the `temurin` JRE
* Create a sha256 sum for the created `gollum.war` file. This sum is echo'd and written to a digest file, which will be attached to the release. The digest file also contains a URL to the …
=> Fix .war generation in release.yml and update actions

.github/workflows/docker-test.yml, test/integration/test_localization.rb
Integration tests are failing consistently on CI and hit-or-miss locally. This suggested a wait time issue. Indeed, it looks as if in some cases the search form was being submitted before the 'send_keys' operation was completed. Added explicit wait time to fix this.
=> Attempt to fix integration tests

.github/workflows/test.yaml
Ruby 3.1 is end of life, drop it in favour of 3.4
=> Update Ruby versions in CI workflow
