lib/gollum/app.rb
=> Remove page file dir from upload path

README.md
Both working now, the textile site was shut down a few years ago, better refer to wiki for format details.
=> Fixed two broken links in README.md

.travis.yml, gollum.gemspec, test/test_app.rb
Pending on https://github.com/gollum/gollum-lib/pull/144 (and release of a new gollum-lib gem)
=> Move to Kramdown and support JRuby

contrib/sysv-debian/init.d/gollum
Adapted from the OpenRC init script in contrib/openrc/init.d/gollum.
=> Added init script for Debian's SysV-style init system

README.md
=> Fixing the vague "running from source" description

lib/gollum/app.rb
hi!
In preview of when there is a sidebar, the sidebar does not appear in the correct position.
I tried to fix this.
=> Fix position of sidebar in preview

lib/gollum/app.rb
This will only work with appropriate changes in gollum-lib, corresponding pull request is here: https://github.com/gollum/gollum-lib/pull/174
=> fixed file renaming issues with page_file_dir

README.md
Relates to https://github.com/gollum/gollum/issues/1105.
=> Adds links to youtube videos in README.

gollum.gemspec
=> Unconditionally add 'test-unit' dependency.

README.md, bin/gollum, gollum.gemspec, lib/gollum/app.rb, lib/gollum/helpers.rb, lib/gollum/public/gollum/css/gollum.css, lib/gollum/public/gollum/javascript/editor/langs/markdown.js, test/test_app.rb
=> Support for emoji

gollum.gemspec, lib/gollum/helpers.rb
https://github.com/gollum/gollum-lib/issues/226
=> Update gemojione to 3.2

README.md
I've made a video to help users without markdown experience get started with gollum.
=> Add another video to README.

test/test_app.rb, test/test_unicode.rb
Closes https://github.com/gollum/gollum/issues/1187
/cc @dometto
=> Skip tests for transliteration for adapters different than grit

bin/gollum, lib/gollum/app.rb, lib/gollum/helpers.rb, test/test_app_helpers.rb
* Activates rename following by default
* Optional override with CLI switches
* Default false on RJGit
=> Follow page renames in history view. Close #565

README.md, bin/gollum
Related to https://github.com/gollum/gollum-lib/pull/275
=> Document how to escape emoji

lib/gollum/templates/editor.mustache
This pull request adds hover text to help users identify the functions of the buttons in the editor.
=> Add hover text to editor buttons

lib/gollum/public/gollum/stylesheets/gollum.scss, lib/gollum/views/pages.rb, test/test_pages_view.rb
Also:
* Show full filename with extension for pages. 
* Distinguish in HTML between file and pages, allowing for different icons in the future.
=> Fix url generation in pages view. 

bin/gollum
See https://github.com/gollum/gollum/issues/1149 and https://github.com/gollum/gollum/pull/1252
=> Solve base_path bugs in bin/gollum. Fixes #1149

lib/gollum/public/gollum/javascript/editor/gollum.editor.js.erb, lib/gollum/public/gollum/stylesheets/editor.scss
=> Fix absense of visual feedback when uploading with drag-and-drop

bin/gollum, lib/gollum/app.rb, lib/gollum/public/gollum/javascript/editor/gollum.editor.js.erb, lib/gollum/public/gollum/javascript/gollum.dialog.js, lib/gollum/public/gollum/javascript/gollum.js.erb, lib/gollum/public/gollum/stylesheets/_layout.scss, lib/gollum/public/gollum/stylesheets/dialog.scss, lib/gollum/templates/layout.mustache, lib/gollum/views/create.rb, lib/gollum/views/edit.rb, lib/gollum/views/layout.rb, lib/gollum/views/page.rb, test/test_allow_editing.rb
This PR makes way for implementing https://github.com/gollum/gollum/issues/1301.
=> Improvements and fixes for file uploading. Prepares for handling of duplicate error.

lib/gollum/app.rb
=> Don't lookup page's last version on edit

lib/gollum/views/page.rb, test/test_page_view.rb
=> Fix breadcrumbs. Resolves #1383

test/test_app.rb
This PR adds a couple of tests for the `upload_file` route. Currently, one of these fails because of an issue in gollum-lib's `Committer#add_to_index` method where a `DuplicatePageError` is not thrown when it should. This should be fixed before the 5.x release.
=> Added tests for file_upload route.

Gemfile, gollum.gemspec, test/helper.rb, test/test_allow_editing.rb, test/test_page_view.rb
Was suffering from some branch pollution (of the example repo's), so better to start with a new branch.
=> Fix Windows assets and tests

lib/gollum/helpers.rb
Opened and merged pull request created by @flowerysong in issue #1472
=> Emoji fix for 5.x

Gemfile, gollum.gemspec, lib/gollum.rb, lib/gollum/app.rb, lib/gollum/templates/compare.mustache, lib/gollum/templates/history.mustache, lib/gollum/views/compare.rb, lib/gollum/views/history.rb, test/test_app.rb
Requires https://github.com/gollum/rugged_adapter/pull/39
=> Track path changes in History. Resolves #1441

lib/gollum/public/gollum/stylesheets/template.scss.erb
=> Clear both sides of the Sidebar float to push the footer down.

lib/gollum/views/overview.rb, lib/gollum/views/page.rb, test/test_overview_view.rb, test/test_page_view.rb
=> Primer CSS breadcrumbs (related to #1394).

README.md, gollum.gemspec, lib/gollum/app.rb, lib/gollum/views/rss.rb, test/test_app.rb, test/test_overview_view.rb
Couldn't stand that we were one of the only wikis without an RSS feed on https://en.wikipedia.org/wiki/Comparison_of_wiki_software
Some pointers in the line comments.
=> Add RSS Feed

Gemfile, gollum.gemspec, lib/gollum.rb
Fortunately, it installs on MRI, so we don't need to make it a conditional dependency.
=> Add Rhino to dependencies

lib/gollum/public/gollum/stylesheets/template.scss.erb
(This is the same as it is in Github wikis.)
=> Let Primer.CSS style <hr> element.

test/test_app.rb
Fails now, requires https://github.com/gollum/gollum-lib/pull/370
=> Add regression test against #1530

bin/gollum, bin/gollum-migrate-tags
Also fix tiny bug in `gollum --version`
=> Fix migrate script path argument. Resolves #1543

bin/gollum, lib/gollum/app.rb, test/test_app.rb
Add tests for https://github.com/gollum/gollum/pull/1536/files and https://github.com/gollum/gollum/pull/1539
=> Add tests for base_path

bin/gollum-migrate-tags, test/test_migrate.rb
Thanks to @bartkamphorst for reporting and suggesting the fix!
=> Fix migration script when using page-file-dir and add test

lib/gollum/public/gollum/javascript/editor/gollum.editor.js, lib/gollum/templates/editor.mustache
As discussed in #527, this adds auto saving to gollum using local storage. It's a direct conversion of the code I posted there, but with jquery used instead of pure javascript, and the code added to the relevant pieces of gollum.editor.js.
=> Add auto save functionality

lib/gollum/app.rb
This PR addresses the issue #1586.
=> Show search page even when no parameters are given

lib/gollum/templates/navbar.mustache, lib/gollum/views/helpers.rb
It addresses the issue #1602.
It also solves the issue #1590 differently from #1593.
=> Ensure page_route starts with a leading slash

lib/gollum/app.rb
*To work, this pull request https://github.com/gollum/gollum-lib/pull/390 needs to be merged first.*
This change will save redirects additions in commits where renaming is saved.
=> Add redirect to rename commit

CONTRIBUTING.md, Gemfile, lib/gollum/app.rb
Dramatically increases test speed, especially on JRuby.
=> Enable static assets during tests

gollum.gemspec
See https://github.com/gollum/gollum/issues/1689#issuecomment-791944608
=> Add webrick dependency

lib/gollum/views/layout.rb, test/test_app.rb
=> Fix query ? in mathjax script path

lib/gollum/app.rb, test/test_app.rb
Resolves #1626
Uses the `text_data` convenience method and adds a test.
=> Load template page as utf-8

lib/gollum/app.rb, lib/gollum/templates/layout.mustache, lib/gollum/views/create.rb, lib/gollum/views/edit.rb, lib/gollum/views/has_math.rb, lib/gollum/views/page.rb
Fixes #1772
I don't have much ruby experience, but I think this patch works as expected. Apart from those that err on master, all test are running.
=> Fix mathjax on edit and create pages

.github/workflows/test.yaml, Gemfile, gollum.gemspec, test/helper.rb, test/test_app.rb
This pull request makes our GitHub Actions test suite workflow run faster. I took this opportunity to also simplify the workflow YAML file.
I started doing this work because of JRuby CI failures. (See #1779.) But then noticed some low-hanging fruit that would improve our test suite runs and maintenance in general.
=> Improve test suite and CI run performance

bin/gollum
=> Set encoding explicitly in bin/gollum

.github/workflows/docker-deploy.yml, Dockerfile
I added platforms to the `build and push` task and added libc6-compat to the docker container.
=> raspberry pi compatibility

.github/workflows/docker-deploy.yml, Dockerfile
removed arm/v6 and v7 because they do not work right now.
=> remove arm/v6 and v7 from the automatic builds

lib/gollum/locales/en.yml, test/capybara_helper.rb, test/helper.rb, test/integration/test_js_errors.rb, test/integration/test_localization.rb, test/test_app.rb
In #1853 we received reports that localized views were breaking for users using the gem on `master`.
These tests should help us catch issues with the localized views.
=> Add Capybara tests for some localized views

README.md, config.rb
=> Add link to sample config.rb

Dockerfile
Resolves #1870.
* Update Docker ruby base image to 3.0
* Add www-data user and run the app as that user
=> Run Docker app as www-data and update ruby

.github/workflows/docker-test.yml, bin/gollum, lib/gollum/app.rb, lib/gollum/templates/layout.mustache
Resolves #1888, see the discussion there.
=> Enable mermaid by default in sandbox mode

LATEST_CHANGES.md, lib/gollum/app.rb, test/test_app.rb
resolves #1906
Folks on that issue sounded okay with this implementation, and imo it's better to break literally no one than to expand the set of paths that clash with user content.
=> Enable downloading page sources with ?raw.

lib/gollum/app.rb
=> Remove unneeded conversion to Commit object.

.github/workflows/release.yml, Gemfile, README.md
Resolves #1947
I've tested this on my [personal fork](https://github.com/dometto/gollum/releases/tag/v17.5b).
=> Build and package war for new releases

Gemfile
We're now passed the issue described in the FIXME.
=> Remove stale comment

lib/gollum/views/overview.rb, test/test_overview_view.rb
Link https://github.com/gollum/gollum/issues/2042
=> Remove unnecessary content in overview page

LATEST_CHANGES.md, README.md, bin/gollum
@bartkamphorst can I have a sanity check on this? Is cleaning up the list of CLI options a little bit worth 'obscuring' the removed options?
=> Remove some cli options. Resolves #1857

README.md
Thank you for contributing to Gollum! You may find help and guidelines for working on this project in [CONTRIBUTING.md](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md).
1. _Please clearly explain the purpose of your PR. Let us know if it introduces a new feature, an enhancement, or fixes a bug._ Improving the README a little bit by adding a ToC and doing other small style fixes.
2. _Please link any issues that your PR addresses._ None
3. _If your PR changes any of the CSS or JavaScript under `lib/gollum/public`, don't forget to update the static asssets as explained [here](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md#updating-static-assets)._ N/A
4. _Finally, please add one line to [LATEST_CHANGES.md](https://github.com/gollum/gollum/blob/master/LATEST_CHANGES …
=> Update README.md: ToC and style fixes
